### ISSUE TITLE
Policy network for different options in discrete environment

### ISSUE THREAD

**Issue by huoliangyu** [mklissa/PPOC#2]
Hi, thanks for your code. However, I am confused about the part of the policy network in mlp_policy.py. Specifically,  I notice that for disperse action space, you use **U.dense** instead of **dense3D2**  function at line 64 as follows:
`pdparam = U.dense(last_out, pdtype.param_shape()[0], "polfinal", U.normc_initializer(0.01))`
Does it mean that different options using the same policy network for  discrete action space but different policy network for continuous  action space?

**Comment by mklissa** [comment]
Hi,
actually the code is currently only implemented for continuous actions. However, the only modification we would need to apply is by replacing "U.dense" by "dense3D2" at line 64 as you pointed out.
