### ISSUE TITLE
default value of timesteps_per_batch

### ISSUE THREAD

**Issue by elitalobo** [mklissa/PPOC#3]
Hi,
Could you please tell me what was the default value of timesteps_per_batch used while benchmarking the performance? 
Its missing in the run_mujoco.py file.

Thanks

**Comment by mklissa** [comment]
Hello, it is 2048, as written in https://github.com/mklissa/PPOC/blob/74daf96ed8a600d4a70d5f552035332a471ff0f9/run_mujoco.py#L34
